on:
  push:
    branches:
      - main

jobs:
    runs-on: ubuntu-latest
    stages:
      - build
      - test
      - deploy

    - stage: build
      displayName: 'Build'
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Build .NET Core project
          run: dotnet build -c Release
        - name: Publish build artifact
          uses: actions/upload-artifact@v2
          with:
            name: myApp
            path: ./myApp/bin/Release/netcoreapp3.1/myApp.dll

    - stage: test
      displayName: 'Test'
      steps:
        - name: Run unit tests
          run: dotnet test -c Release
        - name: Run code analysis
          uses: sonarcloud/sonarcloud-github-action@v1
          with:
            sonarcloud-token: ${{ secrets.SONARCLOUD_TOKEN }}
